# Generated by Django 6.0.2 on 2026-02-23 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['schedule_date', 'start_time'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_stylist_appointment_slot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='stylist_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'BOOKED')), fields=('staff', 'appointment_datetime'), name='unique_staff_appointment_slot_when_booked'),
        ),
        migrations.AddField(
            model_name='staffschedule',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='staffschedule',
            constraint=models.UniqueConstraint(fields=('staff', 'schedule_date', 'start_time', 'end_time'), name='unique_staff_schedule_block'),
        ),
    ]
